### ISSUE TITLE
does not work with redmine 5

### ISSUE THREAD

**Issue by slykereven** [HugoHasenbein/redmine_user_text_box#2]
Hi,
After an upgrade to redmine 5, the plugin does not run in production. With a development environment it does. I tried to look at the code but I'm not proficient in ruby ...
If you have an idea on how to fix the code? Thank you.

Environment:
  Redmine version                5.0.4.stable
  Ruby version                   2.7.4-p191 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7
  Environment                    development
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Redmine-theme-purplemine2 (includes JavaScript)
SCM:
  Git                            2.30.2
  Filesystem                     
Redmine plugins:
  iotbzh                         1.0.0
  iotbzh_menu_links              0.0.1
  redmine_impersonate            2.0.0
  redmine_indicator              0.2.16
  redmine_issue_dynamic_edit     0.9.1
  redmine_lock_out               0.0.1
  redmine_theme_changer          0.6.0
  redmine_user_text_box          0.0.1

```
=> Booting Puma
=> Rails 6.1.7 application starting in production 
=> Run `bin/rails server --help` for more startup options
Exiting
Uncaught exception: cannot load such file -- patches/my_helper_patch
	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
	/opt/redmine-5.0.4/plugins/redmine_user_text_box/lib/redmine_user_text_box.rb:23:in `<top (required)>'
	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `cget'
	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `each'
	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `ls'
```

**Comment by HugoHasenbein** [comment]
Dear Slykereven,

try to change 

require

into

require_relative

in lib/redmine_user_text_box.rb

and tell me, if that resolves the issue.

Best regards

Stephan

**Comment by slykereven** [comment]
Thank you for your feedback,

So I get this:

```
Uncaught exception: uninitialized constant Patches::MyHelperPatch

	/var/lib/gems/2.7.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
```

From what I've read, this is due to the change in the autoloader which now uses the zeitwerk gem.

Regards,
Sylvain

**Comment by slykereven** [comment]
I think it's ok, it works if I initialize the Patches::MyHelperPatch variable in the my_helper_patch.rb file with also require_relative in the redmine_user_text_box.rb file as below:
```

Patches::MyHelperPatch = ''

module RedmineUserTextBox

  module Patches

    module MyHelperPatch

......
```

do you want me to make a merge request or will it be another redmine 5 version?

**Comment by HugoHasenbein** [comment]
No, that seems like un uggly hack. Rather try to

require "redmine_user_text_box"

in init.rb

Best regards

Stephan Wenzel

**Comment by slykereven** [comment]
indeed, I have 3 warnings in the debug console
```
W, [2023-03-06T10:02:00.627449 #2178]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2023-03-06T10:02:00.736354 #2178]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2023-03-06T10:02:00.817373 #2178]  WARN -- : Creating scope :sorted. Overwriting existing method Group.sorted.
```
I tried with your last modification
`require "redmine_user_text_box"` in init.rb
without success for the moment...
But apart from these warnings, I don't see any other concerns about using redmine

**Comment by HugoHasenbein** [comment]
try version 0.1.0 now on github

**Comment by slykereven** [comment]
Hello,

Your fix works well and is certainly cleaner than what I had done, for information I still see the 3 warnings in the console but it works, thanks :)
